### ISSUE TITLE
Uncaught TypeError: Failed to construct 'HTMLElement'

### ISSUE THREAD

**Issue by RapidOwl** [github/catalyst#116]
Hi, this is no doubt a user errror issue rather than a bug, but having read the docs I'm still not sure how to make Catalyst do things.

I'm using:
* The sample from here: https://www.infoq.com/news/2020/12/catalyst-github-web-components/
* Parcel as my build tool (linking my `index.ts` from `index.html`)

The markup renders, but I get this error in the console as soon as the page loads: `Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at new HelloWorldElement (index.ts:4)`

From what I've read this is a common problem when starting developing with web components and people have suggested using the following in your `tsconfig.json`:

```
{
	"compilerOptions": {
		"target": "es2015"
	}
}
```
alternatively
```
{
	"presets": ["es2015"],
	"plugins": ["transform-custom-element-classes", "transform-es2015-classes"]
}
```
in .babelrc.

Neither of these things seem to have helped.

Is there an example repo I can look at? Do you have a recommended build pipeline?

Thanks!

**Comment by koddsson** [comment]
> From what I've read this is a common problem when starting developing with web components

I think this is more a problem with babel/parcel and those tools are transforming native classes into functions. When I set up the example using Parcel, I can see that it's transforming the class into a function like so:

![image](https://user-images.githubusercontent.com/318208/107966819-49e50e80-6fa4-11eb-851a-8fcaf3668182.png)

I think the solution to your issue would be to disable that transform.

**Comment by RapidOwl** [comment]
Thanks for the quick reply. I think my problem is that I used Parcel knowing it did Babel and TypeScript out of the box so thought this would be a quick build pipeline to set up.

Having looked into how to disable this transform, I quickly descended into the madness that is modern JavaScript transpilation and build pipelines (browser versions, targets, presets etc). When in reality, I just want a simple setup that just works so I can see what working with Catalyst is like.

I used an online transpiler on the example linked above and it did not convert the class into a function so that's promising. I think I need to start again with a minimal set up that only does the TypeScript. Maybe Webpack. We'll see!

**Comment by RapidOwl** [comment]
I got it building with Webpack instead (after turning on `experimentalDecorators` in `tsconfig.json` and telling Webpack to use `fullySpecified: false` for imports). I also had to cast `Hello, ${(<HTMLInputElement>this.nameTarget).value}!` the `nameTarget` in the property into a `HTMLInputElement`.

Unfortunately, while it compiles fine, it still doesn't work. This time the error is:
```
index.ts:11 Uncaught TypeError: Cannot read property 'value' of undefined
    at HTMLElement.greet (index.ts:11)
    at HTMLButtonElement.handleEvent (bind.js:71)
```

When I step through, the `nameTarget` property is always undefined. I'm not sure where to go from here.

My repository is here: https://github.com/RapidOwl/catalyst-test.

**Comment by koddsson** [comment]
@RapidOwl I checked that example out and made [a PR to fix the issues you were having](https://github.com/RapidOwl/catalyst-test/pull/1). I think the main issue you were having was that you suffixed all the targets with `Target` and that didn't match the target attribute in the DOM.

**Comment by RapidOwl** [comment]
Brilliant! Thank you!
