### ISSUE TITLE
“Reference guide” has no content

### ISSUE THREAD

**Issue by smockle** [github/catalyst#126]
Repro’d in Safari 14.0.3 and Chrome 89.0.4389.82

e.g. https://github.github.io/catalyst/reference/#attr just says:
> # Reference guide
> ## Reference guide
> Find the reference guide for all our exported functions below

<img width="1237" alt="Screenshot of the empty reference guide page on the Catalyst docs site" src="https://user-images.githubusercontent.com/3104489/110175197-61f3c500-7dcf-11eb-891d-123fec90b460.png">

**Comment by keithamus** [comment]
Looks like our tsdoc tooling broke somehow.

TBH I think we shouldn't bother fixing this. It wasn't that useful and recent Experience Surveys highlighted as much.

The Experience Surveys also highlighted how the guide can be a little wordy and it'd be nice to offer a "Cheat sheet" style quick reference, almost like a flash card to remind folks of syntax & shape without describing detailed semantics, so this seems like a blessing in disguise, I vote we delete the `Reference` page and add a `Cheat Sheet` page instead. We could probably just make one large code sample and leverage the new [docs annotations](https://github.com/github/catalyst/pull/114) to provide useful context on-focus.

**Comment by keithamus** [comment]
Fixed by https://github.com/github/catalyst/pull/130
