### ISSUE TITLE
Reference Gide removed but still has no content

### ISSUE THREAD

**Issue by Nickel-Less** [github/catalyst#132]
Issue: The Reference page was removed here https://github.com/github/catalyst/commit/8ea720843f017e78e75ae3dcdc8f9b9d7353f805
as a solution to https://github.com/github/catalyst/issues/126, but unfortunately there are still links to this broken page within the main site header and banner image.

![image](https://user-images.githubusercontent.com/10601768/112873417-78abd580-9076-11eb-9079-bbb7b5c948d4.png)

**Comment by keithamus** [comment]
Thanks @Nickel-Less. Our plan is to replace this with a cheat-sheet instead. It's a work in progress but will be here in the next few weeks. I'm going to close this in favour of #126 which is effectively the same issue.
