### ISSUE TITLE
Rendering Lists (<ul><li></li></ul>) Patterns?

### ISSUE THREAD

**Issue by okbrown** [github/catalyst#146]
Just read the guide on the main website and found it to be very refreshing and definitely useful in reducing the overhead in working with web components.

But I can't help noticing that most front-end developers will be relying heavily on rendering a list of items on the page and will require a simple and clean manner to go about this. 

I see two routes happening already:
- rendering JS in template strings ``
- or using either @github/jhtml as prescribed
- or something like reactjs etc

What is the advise pattern for this obvious outcome of use?

Additional thought: perhaps this is why SSR is mentioned in the guide too?

Thanks.

**Comment by koddsson** [comment]
> But I can't help noticing that most front-end developers will be relying heavily on rendering a list of items on the page and will require a simple and clean manner to go about this.

Could you go into detail about this use case? For example, would standard HTML elements not be sufficient to render lists?

**Comment by nikordaris** [comment]
i think the question centers around how you take a list of data fetched from an API and iterate over it and render it. the only way i see we can do this is in JS with template strings but i don't know how we avoid re-rendering the entire list when we want to just add a new item to the list.

**Comment by keithamus** [comment]
This issue is over a year old, and I don't think it's an area we're actively trying to address with Catalyst. Thanks for the discussion though!
