### ISSUE TITLE
Testing catalyst components

### ISSUE THREAD

**Issue by BenEmdon** [github/catalyst#159]
What are some practices around testing catalyst components?

Maybe catalyst should include some test helpers or a test framework?

**Comment by keithamus** [comment]
@BenEmdon I think this one might be solved with the new Testing guide page (added in #218). Think it’s enough to close this one out?

**Comment by keithamus** [comment]
I'll close this as I think #218 successfully address the issues, but let me know if it doesn't and we can re-open!
