### ISSUE TITLE
lib folder missing in 1.4.0

### ISSUE THREAD

**Issue by jdanyow** [github/catalyst#216]
Looks like the lib folder wasn't published in 1.4.0. 

Noticed this in a local install with npm 8.5.0 but here's a screen cap from jsdelivr

https://www.jsdelivr.com/package/npm/@github/catalyst?version=1.4.0
<img width="787" alt="CleanShot 2022-04-30 at 13 34 44@2x" src="https://user-images.githubusercontent.com/1306747/166121765-dd5780b5-4572-4352-9293-95f908189a98.png">

vs 
https://www.jsdelivr.com/package/npm/@github/catalyst?version=1.3.2
<img width="772" alt="CleanShot 2022-04-30 at 13 37 02@2x" src="https://user-images.githubusercontent.com/1306747/166121831-5bf22b16-6f38-4e55-8aaf-4336a30ac15b.png">

**Comment by keithamus** [comment]
Thanks @jdanyow for spotting this! Looks like our publish workflow wasn’t running `build` (just coincidentally though `test`, which was recently changed) 😬 

I’ve fixed this in https://github.com/github/catalyst/commit/e8be4f61ce233268cfb5d29f9cc798c5864f18d3 and v1.4.1 should be out shortly.

**Comment by keithamus** [comment]
Uhhh and by `v1.4.1` I mean `v1.4.2` 😂

**Comment by jdanyow** [comment]
been there more often than I'd like to admit 🙌
