### ISSUE TITLE
Build fail using vite vanilla-ts template

### ISSUE THREAD

**Issue by jeromebon** [github/catalyst#273]
I believe I followed all the steps in https://github.github.io/catalyst/guide/you-will-need/ (create a ts project and add experimentalDecorators) yet I get an error when I try to build a new project.

typescript version: 4.7.4
vite version: 3.0.8
catalyst version: 1.6.0

# Steps to reproduce

1) Create a new project
> npm create vite@latest
Pick vanilla-ts

2) Add experimentalDecorators to tsconfig.json. The full tsconfig look like this:
```
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "lib": ["ESNext", "DOM"],
    "moduleResolution": "Node",
    "strict": true,
    "sourceMap": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "noEmit": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "skipLibCheck": true,
    "experimentalDecorators": true,
  },
  "include": ["src"]
}
```

3) Create an element in main.ts, this example is from capacitor's doc
```
import { controller, target } from "@github/catalyst"

@controller
class HelloWorldElement extends HTMLElement {
  @target output: HTMLElement

  greet() {
    this.output.textContent = `Hello, world!`
  }
}
```

4) Run `npm run build`. Ts fails to compile:
```
src/main.ts:4:7 - error TS6196: 'HelloWorldElement' is declared but never used.

4 class HelloWorldElement extends HTMLElement {
        ~~~~~~~~~~~~~~~~~

src/main.ts:5:11 - error TS2564: Property 'output' has no initializer and is not definitely assigned in the constructor.

5   @target output: HTMLElement
            ~~~~~~

Found 2 errors in the same file, starting at: src/main.ts:4
```

**Comment by jeromebon** [comment]
If I set noUnusedLocals to false then the first error is fixed.
If I set strict to false then the second one is solved.

Is there workarounds to use catalyst with theses options set to true ?

**Comment by keithamus** [comment]
I'm going to close this issue, as I believe the above comment should solve the issues mentioned. If you feel otherwise please let me know, and perhaps we can break out each individual area of friction into a separate issue.
