### ISSUE TITLE
Stimulus action `@window` or `@document` equilvalent? 

### ISSUE THREAD

**Issue by 100phlecs** [github/catalyst#311]
I noticed in the guides as well as the `bind.ts` tests that one cannot register actions to listen to global events.

What's the `catalyst` way of solving this?

For example, one may want to listen for a `scroll` event in the global scope, or a global event from a library like Turbo, such as `turbo:before-visit@window` to persist state changes between HTML pages that have the same custom element. I also use it to register window keybindings for when the custom element will not be in focus.

One could very well register it within the custom element with `window.addEventListener` -- but one of the main things attractive about Stimulus is that it handles event registration and destruction for you

Are there plans to support this, or if not, what is your suggested strategy for dealing with event listeners on the global scope?

**Comment by keithamus** [comment]
We wanted to avoid global event listeners as we find they do more harm than good, for the most part. There seems to be two classes of global event listeners:

 - Using broad event delegation, e.g. listening for `click` on the `window` and checking the `target`. Event delegation
