### ISSUE TITLE
@github/jtml availability on Github Package

### ISSUE THREAD

**Issue by georges-gomes** [github/catalyst#83]
It seems that `@github/jtml` is published on `npm` but `@github/catalyst` is published on `github packages`.
Would be eassier to have both on Github Packages so the npm configation for `@github` registry is straight forward.

Thanks

**Comment by georges-gomes** [comment]
Or both on `npm`, works as well 😄

**Comment by keithamus** [comment]
Thanks for pointing this out! I'll work to get jtml released as OSS, and look at how we can publish to both GPR and the npm registry.

**Comment by georges-gomes** [comment]
Thanks!

**Comment by keithamus** [comment]
https://github.com/github/catalyst/pull/84 has pushed `@github/catalyst` to npm. Releasing `jtml` will take a little longer.

**Comment by keithamus** [comment]
`@github/jtml` is now open source!

https://github.com/github/jtml
